Add a function to detect if the system runs a dual PAM stack
yast/yast-pam pull request #28
Opened 2022-03-28 16:17 UTC by scabrero

Related to bsc#1190873

Signed-off-by: Samuel Cabrero <scabrero@suse.de>

2022-04-12 12:08 UTC, ancorgs requested changes
Please see comments.

By the way, following the conversation in the bug report it looks to me like fixing the problem in YaST is a suboptimal solution.

2022-04-12 12:08 UTC, ancorgs commented on src/modules/Pam.rb
> +      if FileUtils.Exists("/lib/security") && FileUtils.Exists("/lib/libpam.so.0")
Sorry for being nitpicking but I don't see the effective difference between these four lines of code:

```ruby
def somehing
  if condition1 && condition2
    return true
  end
  false
end
```

and a more readable one-liner like:

```ruby
def somehing
  condition1 && condition2
end
```

And looks it's not only me, Rubocop is also complaining about that code.

2022-04-12 12:08 UTC, ancorgs commented on package/yast2-pam.spec
> +Version:        4.4.1
So you are intentionally submitting this only to Tumbleweed. Isn't it?

2022-04-25 10:34 UTC, scabrero commented
> Please see comments.
> 
> By the way, following the conversation in the bug report it looks to me like fixing the problem in YaST is a suboptimal solution.

Ok.

2022-04-25 10:34 UTC, closed without merging